version: "3.8"
services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "dev"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./volumes/database:/var/lib/mysql
  libsql:
    image: libsql
