const date = new Date();
export const mockData = [
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
  {
    anotherUserID: "Emily",
    senderName: "Meen",
    lastestMessage: "Hi what are you doing I miss you",
    createdAt: date.toString(),
    imageUrl: "https://picsum.photos/id/237/200/300",
  },
];
