name: deploy website
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install vercel cli
        run: npm i -g vercel
      - name: Deploy
        run: vercel --prod --token $VERCEL_TOKEN --yes --scope onfirebytes-projects deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
